In [2]:
import pandas as pd
import numpy as np
from shared import load_data, evaluate_model, evaluate_rating_metrics

In [3]:
train_df, test_df, restaurants_df = load_data()
test_users = test_df['user_id'].unique().tolist()
all_restaurants = restaurants_df['business_id'].unique().tolist()

In [4]:
global_mean = train_df['stars'].mean()

user_means = train_df.groupby('user_id')['stars'].mean()
user_bias = user_means - global_mean
user_bias_dict = user_bias.to_dict()

item_means = train_df.groupby('business_id')['stars'].mean()
item_bias = item_means - global_mean
item_bias_dict = item_bias.to_dict()

print(f"Global Mean: {global_mean:.4f}")

Global Mean: 3.9770

In [5]:
def predict_rating(user, item):
    b_u = user_bias_dict.get(user, 0.0)
    b_i = item_bias_dict.get(item, 0.0)

    pred = global_mean+ b_u + b_i

    return np.clip(pred, 1.0, 5.0)

test_df['predicted_stars'] = test_df.apply(lambda row: predict_rating(row['user_id'], row['business_id']), axis=1)

rating_metrics = evaluate_rating_metrics(test_df['stars'], test_df['predicted_stars'])
print("Rating Prediction Performance:")
print(f"MAE: {rating_metrics['MAE']:.4f}")
print(f"RMSE: {rating_metrics['RMSE']:.4f}")

Rating Prediction Performance:
MAE: 0.8636
RMSE: 1.1764

In [11]:
predictions = {}

for user in test_users:
    b_u = user_bias_dict.get(user, 0.0)

    user_item_scores = []
    for item in all_restaurants:
        b_i = item_bias_dict.get(item, 0.0)
        score = global_mean + b_u + b_i
        user_item_scores.append((item, score))

    user_item_scores.sort(key=lambda x: x[1], reverse=True)

    top_30_items = [item for item, score in user_item_scores[:30]]
    predictions[user] = top_30_items



print("\nRanking Performance:")
print("-" * 30)
for metric_name, score in ranking_metrics.items():
    print(f"{metric_name:<10}: {score:.4f}")

Ranking Performance:
------------------------------
Hit@10    : 0.0033
Hit@20    : 0.0081
Hit@30    : 0.0150
NDCG@10   : 0.0013
NDCG@20   : 0.0025
NDCG@30   : 0.0039

In [14]:
ranking_metrics = evaluate_model(predictions, test_df)
results_df = pd.DataFrame([ranking_metrics]).round(4)
results_df.index = ['User-Item Bias (Ranking)']
display(results_df)

                          Hit@10  Hit@20  Hit@30  NDCG@10  NDCG@20  NDCG@30
User-Item Bias (Ranking)  0.0033  0.0081   0.015   0.0013   0.0025   0.0039

In [12]:
rating_metrics = evaluate_rating_metrics(test_df['stars'], test_df['predicted_stars'])
rating_df = pd.DataFrame([rating_metrics]).round(4)
rating_df.index = ['User-Item Bias (Ratings)']
display(rating_df)

                             MAE    RMSE      R2
User-Item Bias (Ratings)  0.8636  1.1764  0.1111